kafka:
  addr: kafka-cluster:9092
  group: agent-group
  task_topic: tasks
  status_topic: task-status
data-provider:
  addr: data-provider:8080
  useTLS: false
  caCert: ""
  grpcServerName: ""
agent:
  grpc:
    network: "tcp"
    addr: 0.0.0.0:8080
    useTLS: false
    cert: ""
    key: ""
    ca: ""