api-service:
  http:
    addr: 0.0.0.0:8080
agent:
  addr: agent:8080
  useTLS: false
  caCert: ""
  grpcServerName: ""
data-provider:
  addr: data-provider:8080
  useTLS: false
  caCert: ""
  grpcServerName: ""