name: Update, Build and Push Submodules

on:
  push:
    branches:
      - main
      - master
  schedule:
    - cron: '0 0 * * *'  # Daily check

permissions:
  contents: write
  pull-requests: read

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: true
          fetch-depth: 0

      - name: Pull and update submodules recursively
        run: |
          git submodule update --init --recursive
          git submodule update --recursive --remote

      - name: Commit changes to the main repository
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git add .
          git commit -m "Update submodules" || echo "No changes to commit"

      - name: Push changes
        run: |
          git push

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v1

      # - name: Login to Harbor
      #   uses: docker/login-action@v1
      #   with:
      #     registry: harbor.devops-teta.ru
      #     username: ${{ secrets.HARBOR_USERNAME }}
      #     password: ${{ secrets.HARBOR_PASSWORD }}

      # - name: Install jq
      #   run: sudo apt-get install -y jq

      # - name: Build and push Docker images
      #   run: |
      #     cd .docker

      #     svc_list=$(docker compose config --format json | \
      #         jq '.services | to_entries | map(select(.value.build)) | .[].key' | \
      #         tr -d \")

      #     echo "Will build the following services:"
      #     echo $svc_list
      #     
      #     echo "$svc_list" | while read svc; do
      #         echo "Building $svc..."
      #         docker compose build $svc
      #         echo "Tagging $svc..."
      #         docker tag docker-$svc:latest harbor.devops-teta.ru/bergman-valery/$svc
      #         echo "Pushing $svc to Harbor..."
      #         docker push harbor.devops-teta.ru/bergman-valery/$svc
      #     done
