name: Update Submodules

on:
  push:
    branches:
      - main
      - master
  schedule:
    - cron: '0 0 * * *'  # Daily check

permissions:
  contents: write
  pull-requests: read

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: true
          fetch-depth: 0

      - name: Pull and update submodules recursively
        run: |
          git submodule update --init --recursive
          git submodule update --recursive --remote

      - name: Commit changes to the main repository
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git add .
          git commit -m "Update submodules" || echo "No changes to commit"

      - name: Push changes
        run: |
          git push
